version: '3'

networks:
  sun-iot-things:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24


services:
  web:
    image: fraunhoferiosb/frost-server:2.0
    container_name: FROST-SERVER
    environment:
      - serviceRootUrl=http://localhost:8080/FROST-Server
      - plugins.multiDatastream.enable=true
      - http_cors_enable=true
      - http_cors_allowed_origins=*
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
      - persistence_db_username=sensorthings
      - persistence_db_password=ChangeMe
      - persistence_autoUpdateDatabase=true
    ports:
      - 8080:8080
      - 1883:1883
    networks:
      sun-iot-things:
        ipv4_address: 172.22.0.2
    depends_on:
      - database
    restart: always

  database:
    image: postgis/postgis:14-3.2-alpine
    container_name: POSTGIS-BD
    environment:
      POSTGRES_DB: sensorthings
      POSTGRES_USER: sensorthings
      POSTGRES_PASSWORD: ChangeMe
    ports:
      - 5432:5432
    volumes:
      - ./postgis_volume:/var/lib/postgresql/data
    networks:
      sun-iot-things:
        ipv4_address: 172.22.0.3
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: PG_ADMIN
    environment:
      PGADMIN_DEFAULT_EMAIL: sensorthings@iot.com
      PGADMIN_DEFAULT_PASSWORD: ChangeMe
    ports:
      - 8081:80
    networks:
      sun-iot-things:
        ipv4_address: 172.22.0.4
    restart: always

  grafana:
    image: grafana/grafana-oss
    container_name: GRAFANA
    ports:
      - 3000:3000
    volumes:
      - grafana_storage:/var/lib/grafana
    networks:
      sun-iot-things:
        ipv4_address: 172.22.0.5
    restart: unless-stopped
volumes:
  grafana_storage: {}
